### ISSUE TITLE
Spaces in paths lead to errors

### ISSUE THREAD

**Issue by fmeyenhofer** [diffplug/matlabcontrol#11]
Hi 

there is an old issue
https://code.google.com/archive/p/matlabcontrol/issues/26

so the package can't be loaded if there are spaces in the path. Was this fixed since the migration to github?

**Comment by nedtwigg** [comment]
Probably not.  A lot of other stuff got fixed, but I don't recall bumping
into this.

On Friday, July 1, 2016, felix cc notifications@github.com wrote:

> Hi
> 
> there is an old issue
> https://code.google.com/archive/p/matlabcontrol/issues/26
> 
> so the package can't be loaded if there are spaces in the path. Was this
> fixed since the migration to github?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/diffplug/matconsolectl/issues/11, or mute the thread
> https://github.com/notifications/unsubscribe/ACyhwAvnich2DgkhS0BlAtLLjTq2VQ0Nks5qRM-TgaJpZM4JC7OY
> .

## 

Ned Twigg
Lead Software Architect, DiffPlug LLC
540-336-8043
340 S Lemon Ave #3433, Walnut, CA 91789

**Comment by fmeyenhofer** [comment]
I encountered this error in our project
https://github.com/knime-mpicbg/knime-scripting/issues/63
I am currently trying to reproduce it within matlabcontrol. Weird thing is that this problem happens not from within the debug mode of eclipse, but only once the plugin is compiled.

**Comment by fmeyenhofer** [comment]
The error message idicates that it's thrown here:
https://github.com/diffplug/matconsolectl/blob/602cbded5f9ae1b1470bbe07fa4d246d12ede9c3/src/matlabcontrol/Configuration.java#L261-L267

Do you see any problems to convert white spaces to `%20`  in the following line?
https://github.com/diffplug/matconsolectl/blob/602cbded5f9ae1b1470bbe07fa4d246d12ede9c3/src/matlabcontrol/Configuration.java#L208

**Comment by nedtwigg** [comment]
I think [this commit](https://github.com/diffplug/matconsolectl/commit/72bdf340b73b7893e4fab33a38ac53f3864587b8) oughtta fix it.

I've deployed the snapshot.  Wanna see if it fixes your issue?

Repo: `https://oss.sonatype.org/content/repositories/snapshots/`
Artifact: `com.diffplug.matsim:matconsolectl:4.5.0-SNAPSHOT`

**Comment by fmeyenhofer** [comment]
Nice, that did the trick.
Cheers!

**Comment by nedtwigg** [comment]
Glad it worked.  Just published version `4.4.2` with this fix.  `4.5.0-SNAPSHOT` might have new features / bugs added in the future.

**Comment by nedtwigg** [comment]
#15 seems to indicate that this sorta fixed it, but not all the way.  4.4.3 (to be released in minutes) is even more robust.
