### ISSUE TITLE
MatConsoleCtl Calling Simulink or Matlab Compiled Executables

### ISSUE THREAD

**Issue by danasmoot** [diffplug/matlabcontrol#13]
I am using MatConsoleCtl to run calculations and add plotting features to a Java application and wanted to know if it supports calling of Simulink files or executables created by the MATLAB Compiler?

The first problem is that I have a Simulink application that I would also like to connect to the Java application and was hoping to use the same API to access the calculations that it defines.

The second is that I would like to deploy the Java application to people that do not necessarily have a Matlab license and was hoping that they could use the free Matlab runtime to run the scripts that our Java app calls.

Thanks,
Dana

**Comment by nedtwigg** [comment]
MatConsoleCtl can be used to interact with Simulink models, through the standard [MATLAB Simulink API](https://www.mathworks.com/help/simulink/functionlist.html?s_cid=doc_ftr).  At DiffPlug, we use this API [with MatConsoleCtl extensively](https://docs.diffplug.com/1.8.7/ViewerDiffers/SimulinkViewerDiffer/TrackInMatlab/).

As for the "free Matlab runtime", I guess you're referring to [this](https://www.mathworks.com/products/compiler/mcr/)?  Unfortunately I don't know anything about it, but if you find anything out it'd be great to know.

**Comment by danasmoot** [comment]
Thanks for the reply.  I will look into the MATLAB Simulink API.  Since all my Java app knows how to do is call a specifically formatted .m file, I can probably just create a .m wrapper to call the Simulink API.

And yes, that is the MATLAB runtime I was referring too.  If I find anything I will post that.

Thanks

**Comment by nedtwigg** [comment]
Feel free to reopen if you find any more information.
