### ISSUE TITLE
remote functionalities and multiple matlab sessions opened

### ISSUE THREAD

**Issue by AndreGuerra123** [diffplug/matlabcontrol#19]
Hello, 

Remote actions;
I would like to know, first of all, if it is possible to run a java method which connects to a matlab session in another computer (remotely). For instance, I have several agents classes in a distributed network which have to make operations in Matlab and I would require these agents to pass arguments to a single Matlab session on a single machine (in which Matlab is running).

Multiple Sessions;
When my java methods communicate to Matlab they always open multiple Matlab sessions even when the .setUsePreviouslyControlledSession(true) is set. Is there a way to prevent this?

**Comment by nedtwigg** [comment]
Multiple sessions: Try calling `.setPort(SOME_NUMBER)` in addition to `usePreviouslyControlledSession`.

Remote actions: MatConsoleCtl doesn't have any built-in functionality for orchestrating sessions on remote machines.  If you build it, we'd be happy to merge it.

**Comment by nedtwigg** [comment]
Feel free to reopen for further discussion.
