### ISSUE TITLE
unable to gradle build the project

### ISSUE THREAD

**Issue by sagar3047** [diffplug/matlabcontrol#24]
getting certificate related errors for various dependencies

**Comment by sagar3047** [comment]
@nedtwigg @subes @gazialankus @rkurmann 
could someone please guide how to get the gradle build running
![image](https://github.com/diffplug/matconsolectl/assets/35396383/734d6f9d-a6d6-4e7c-8659-6bd87b2044b9)

**Comment by subes** [comment]
From what I know bintray does not exist anymore. Try removing everything related to bintray from [build.gradle](https://github.com/diffplug/matconsolectl/blob/0d5b320f743f7c6d49ea11c5652cb61852e2d3dd/build.gradle#L6). Maybe that way gradle won't use the bintray mirror anymore and instead try to download from maven central (which should succeeed).

**Comment by sagar3047** [comment]
tried commenting out the dependencies from build.gradle one-after-another but almost all of them try to use bintray mirror
e.g.
plugins {
	// osgi
	id "org.jruyi.osgibnd" version "0.4.0"
	// code formatting
	//id "com.diffplug.gradle.spotless" version "3.1.0"
	// bintray uploading
	//id "com.jfrog.bintray" version "1.3.1"
	// for downloading JRE6
	id "de.undercouch.download" version "2.0.0"
}
after this  get the below issue
![image](https://github.com/diffplug/matconsolectl/assets/35396383/d7433be7-6801-4949-9daf-74b952cc6dc3)

**Comment by subes** [comment]
Just continue minimizing the gradle files. You also don't need osgibnd unless you want to deploy as OSGI artifacts.

**Comment by subes** [comment]
Most likely the gradle file was written for an ancient gradle version and might need some tweaks to run with newer versions. And older gradle versions won't run on newer JVMs (things I hate about gradle). :D
Worst case it should be relatively simple to create a minimal pom to build the project with maven.

**Comment by sagar3047** [comment]
Adding the below piece of code resolved the issue related to jcenter though
_```
all { ArtifactRepository repo ->
  if(repo instanceof MavenArtifactRepository){
    def url = repo.url.toString()
    if (url.startsWith('https://jcenter.bintray.com/')) {
      remove repo
    }
  }
}
```_

There are other issues after that which I am trying to fix..like below

![image](https://github.com/diffplug/matconsolectl/assets/35396383/00f9e14f-249d-4e4d-ab9e-bba469099ad1)

**Comment by nedtwigg** [comment]
We've recently implemented a sort of template (https://github.com/diffplug/blowdryer-diffplug) across all our open source projects at DiffPlug. I could apply that template here, but we haven't had any internal need to update this library, the existing functionality has been fine for us.

What prompts you to work on the codebase?

**Comment by sagar3047** [comment]
actually we are using this library(jars) in our application. Recently we have a bug report :  
_After connecting to MATLAB instance to process  Simulink models, there are some temp. files created inside the system temp dir. which are not deleted after MATLAB is disconnected._ 
Hence the plan is to push all such temp. files generated during execution into a custom temp directory & get rid of the same after processing.
Thus we are planning to pass a temp. dir. location inside the class MatlabProxyFactoryOptions & eventually use it inside RemoteMatlabProxyFactory::createProcess method.
 We are trying to test change this change locally.

**Comment by sagar3047** [comment]
was able to build the project after a few tweaks in the build file : commenting out deprecated plugins, upgrading etc.
But I am unable to add this jar as a dependency in my project since the jar's MANIFEST.MF file is not correct or adhering to OSGI specifications. 
I have removed id "**org.jruyi.osgibnd**" version "0.4.0" plugin from the gradle file since it is no longer existing probably which is why the MANIFEST.MF file is not generated correctly.
I have tried using the latest version of the plugin & also tried an alternative plugin "**biz.aQute.bnd.builder"** but in vain.

Please suggest if there is a solution to this.

**Comment by sagar3047** [comment]
plugins {
	// osgi
	// id "org.jruyi.osgibnd" version "0.4.0"
	id "biz.aQute.bnd.builder" version "6.4.0"
	// code formatting
	id "com.diffplug.gradle.spotless" version "3.1.0"
	// bintray uploading
	id "com.jfrog.bintray" version "1.3.1"
	// for downloading JRE6
	id "de.undercouch.download" version "latest.release"
}

repositories {
	mavenCentral()
}

//////////
// JAVA //
//////////
apply plugin: 'java'
sourceSets {
	main { java {
			srcDir 'src'
	} }
	test { java {
			srcDir 'test'
	} }
}
sourceCompatibility = VER_JAVA
targetCompatibility = VER_JAVA

dependencies {
	testImplementation "junit:junit:${VER_JUNIT}"
}

processResources {
	from ('src') {
		exclude '**/*.java'
	}
}

////////////////////
// MATLAB TESTING //
////////////////////
// standard `gradlew test` can't handle tests which require a MATLAB installation
test {
	// test
	useJUnit {
		excludeCategories 'matlabcontrol.MatlabRequired$Interactive'
		excludeCategories 'matlabcontrol.MatlabRequired$Headless'
	}
}

task testMatlabHeadless(type: Test) {
	useJUnit {
		includeCategories 'matlabcontrol.MatlabRequired$Headless'
	}
}
task testMatlabInteractive(type: Test) {
	useJUnit {
		includeCategories 'matlabcontrol.MatlabRequired$Interactive'
	}
}
task testMatlabAll(dependsOn: [test, testMatlabHeadless, testMatlabInteractive])

//////////
// OSGI //
//////////

// delete the old manifest to ensure there's no caching or merging going on
jar.doFirst {
	project.file('META-INF/MANIFEST.MF').delete()
}

jar.manifest {
	attributes (
		'Export-Package': 'matlabcontrol.*,!matlabcontrol.internal.*,!matlabcontrol.demo.*',
		'Bundle-SymbolicName': "${project.group}.${project.name}",
		'Bundle-Vendor': 'DiffPlug',
		'Bundle-DocURL': "https://github.com/${project.org}/${project.name}",
		'Bundle-License': "https://github.com/${project.org}/${project.name}/blob/v${project.version}/LICENSE",
		'Import-Package': '!com.mathworks.jmi',
		'Main-Class': 'matlabcontrol.demo.DemoMain',
		'-includeresource': "matlabcontrol=${sourceSets.main.output.classesDirs}/matlabcontrol,${sourceSets.main.output.resourcesDir}",
		'-removeheaders': 'Bnd-LastModified,Bundle-Name,Created-By,Tool,Private-Package',
		'-savemanifest': project.file('META-INF/MANIFEST.MF'),
	)
}

// manifests are only generated when the java files change - not if manifest properties change
// this task forces the manifests to regenerate
task refreshManifest(dependsOn: jar)
gradle.taskGraph.whenReady { taskGraph ->
	if (taskGraph.hasTask(refreshManifest)) {
		jar.outputs.upToDateWhen { false }
	}
}

////////////
// JAVA 6 //
////////////

// matlabcontrol requires at least Java 1.6,
// but older MATLABs run on even older versions

// URL for downloading the JRE6
// others available here, OS doesn't matter: https://github.com/alexkasko/openjdk-unofficial-builds#openjdk-6-build-30
def JDK6_URL = 'https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.6.0-unofficial-b30-windows-i586-image.zip'
def JDK6_SHA_256 = '8a119a8c9b2ecc48e8457738f57b251e6265b2c0fb232de0ff6fddce0f127045'
// place where the JRE6 will end up
def JDK6_DIR = "${buildDir}/jdk"
def JDK6_DST = "${JDK6_DIR}/jdk.zip"
def JRE6_HOME = "${buildDir}/jdk/openjdk-1.6.0-unofficial-b30-windows-i586-image/jre"

import de.undercouch.gradle.tasks.download.Download;
import de.undercouch.gradle.tasks.download.Verify;

task downloadJRE6(type: Download) {
	src JDK6_URL
	dest JDK6_DST
	overwrite false
}

task verifyJRE6(dependsOn: downloadJRE6, type: Verify) {
	src downloadJRE6.dest
	algorithm 'SHA-256'
	checksum JDK6_SHA_256
}

task unzipJRE6(dependsOn: verifyJRE6, type: Copy) {
	from zipTree(downloadJRE6.dest)
	into JDK6_DIR
}

// Best bet is to stay at 1.6
sourceCompatibility = 1.7
targetCompatibility = 1.7 

/////////////
// ECLIPSE //
/////////////
apply plugin: 'eclipse'
eclipse {
	project {
		natures 'org.eclipse.pde.PluginNature'
		natures 'org.eclipse.jdt.core.javanature'

		buildCommand 'org.eclipse.jdt.core.javabuilder'
		buildCommand 'org.eclipse.pde.ManifestBuilder'
		buildCommand 'org.eclipse.pde.SchemaBuilder'
	}
	classpath {
		downloadSources true
		downloadJavadoc true
	}
	jdt {
		sourceCompatibility VER_JAVA
		targetCompatibility VER_JAVA
	}
}
// always create fresh projects
tasks.eclipse.dependsOn(cleanEclipse)

///////////
// MAVEN //
///////////
apply plugin: 'maven-publish'

// the package of the jmi stub (which we're going to leave out of all the jars we make)
def JMI_STUB = 'com/mathworks/jmi/**'

// make a source jar
task sourcesJar(type: Jar) {
	archiveClassifier = 'sources'
	from sourceSets.main.allJava
	exclude(JMI_STUB)
}

// Where it's possible to name parameters and methods clearly enough
// that javadoc is not necessary, why make the code bigger?
//
// Thus, no javadoc warnings.
def makeLink = { url, text -> "<a href=\"${url}\" style=\"text-transform: none;\">${text}</a>" }
def javadocInfo = '<h2>' + makeLink("https://github.com/${org}/${name}", "${group}:${name}:${version}") +
' by ' + makeLink('http://www.diffplug.com', 'DiffPlug') + '</h2>'
javadoc {
	options.addStringOption('Xdoclint:none', '-quiet')
	options.header javadocInfo
	options.footer javadocInfo
	options.links('https://docs.oracle.com/javase/6/docs/api/')
}

task javadocJar(type: Jar, dependsOn: javadoc) {
	archiveClassifier = 'javadoc'
	from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
}

////////////////
// PUBLISHING //
////////////////
def isSnapshot = project.version.endsWith('-SNAPSHOT')
// pulls the credentials from either the environment variable or gradle.properties
def cred = {
	if (System.env[it] != null) {
		return System.env[it]
	} else if (project.hasProperty(it)) {
		return project[it]
	} else {
		return 'unknown_' + it
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifact sourcesJar
			artifact javadocJar
			pom.withXml {
				// findbugs annotations should have scope "provided"
				asNode().dependencies.'*'.findAll() { it.groupId.text() == 'com.google.code.findbugs' }.each() { it.scope*.value = 'provided' }
				// add MavenCentral requirements to the POM
				asNode().children().last() + {
					resolveStrategy = Closure.DELEGATE_FIRST
					name project.name
					description project.description
					url "https://github.com/${project.org}/${project.name}"
					scm {
						url "https://github.com/${project.org}/${project.name}"
						connection "scm:git:git://github.com/${project.org}/${project.name}"
						developerConnection "scm:git:ssh:git@github.com/${project.org}/${project.name}"
					}
					licenses {
						license {
							name 'New BSD License'
							url 'https://github.com/diffplug/matconsolectl/blob/v4.4.0/LICENSE'
							distribution 'repo'
						}
					}
					developers {
						developer {
							id 'nedtwigg'
							name 'Ned Twigg'
							email 'ned.twigg@diffplug.com'
						}
					}
				}
			}
		}
	}
	if (isSnapshot) {
		// upload snapshots to oss.sonatype.org
		repositories { maven {
			url = 'https://oss.sonatype.org/content/repositories/snapshots'
			credentials {
				username = cred('nexus_user')
				password = cred('nexus_pass')
			}
		} }
	}
}

if (!isSnapshot) {
	// upload releases to bintray and then mavenCentral
	bintray {
		user = cred('bintray_user')
		key = cred('bintray_pass')
		publications = ['mavenJava']
		publish = true
		pkg {
			repo = 'opensource'
			name = project.name
			userOrg = project.org
			version {
				name = project.version
				mavenCentralSync {
					user = cred('nexus_user')
					password = cred('nexus_pass')
				}
			}
		}
	}

	publish.dependsOn(bintrayUpload)
	bintrayUpload.dependsOn(['generatePomFileForMavenJavaPublication', jar, sourcesJar, javadocJar])
}

// helps external scripts detect version
task printVersion {
	doLast {
		println version
	}
}

allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.incremental = true
    }

}

**Comment by subes** [comment]
I am sure gradle should have some way to supply a MANIFEST.MF manually (just get one from an older release that contains the OSGI directives and let gradle package that into the jar). Or just replace the MANIFEST.MF manually in the jar before uploading it manually to nexus/artifactory.

**Comment by nedtwigg** [comment]
I just merged a modernized build. Sorry for all the changes, but it's the bare minimum I would need in order to publish a new version to mavenCentral. I removed the OSGi manifest completely because we don't use OSGi internally anymore. If you need OSGi metadata, feel free to add it back in.
