### ISSUE TITLE
Introduce option to pass an environment (Map<K,V>) to the process builder spawning MATLAB instance.

### ISSUE THREAD

**Issue by sagar3047** [diffplug/matlabcontrol#26]
Create a property in "MatlabProxyFactoryOptions.java" to allow a Map representing an environment which the Java process builder would use during creating of MATLAB proxy instance.
This would allow the caller to pass some properties e.g. a custom temporary location to the MATLAB process.

**Comment by nedtwigg** [comment]
I'm happy to merge and release a PR for this feature.

**Comment by sagar3047** [comment]
@nedtwigg have created a PR for the enhancement request..kindly have a look on the changes

**Comment by sagar3047** [comment]
@nedtwigg thanks for reviewing & incorporating the changes to the repo.
any plans to release the next version of the library(may be 4.7.0) so that we could consume the official released version(we have currently integrated a locally built copy of the jar) ?

**Comment by nedtwigg** [comment]
Thanks for the PR! Published in `4.6.1`.
