### ISSUE TITLE
Implementation guide and errors

### ISSUE THREAD

**Issue by AndreaPerrello** [diffplug/matlabcontrol#4]
I was trying to implement MatConsoleCtl downloading the demo, but I found out that Eclipse was reporting some errors in Configuration.java and JMIWrapper.java classes, in lines of import edu.umd.cs.findbugs.annotations.suppressfbwarnings.
I was wondering if there is some tips about a proper installation of the library.

**Comment by nedtwigg** [comment]
Are you working from source, or from a downloaded jar?

If you're working from MatConsoleCtl's source, then `gradlew eclipse` will create a project which is configured correctly.

If you're working from the downloaded jar, you might need
- `com.google.code.findbugs:annotations:3.0.0`
- `com.google.code.findbugs:jsr305:3.0.0`

which are both on maven central.

They're only needed for compilation, so you shouldn't need them unless you're working from source.

**Comment by AndreaPerrello** [comment]
Okay, I'll try and let you know if I'll get some other troubles or if It
will work fine. Thank you again for your suggestions.

**Comment by AndreaPerrello** [comment]
Using the .jar it works well. I just downloaded
- mvnrepository.com/artifact/com.diffplug.matsim/matconsolectl
- mvnrepository.com/artifact/com.google.code.findbugs/annotations/3.0.0
- mvnrepository.com/artifact/com.google.code.findbugs/jsr305/3.0.0

and builded my Eclipse project path adding them.

(I didn't find the MatConsoleCtl jar out there on GitHub, I had to google it).

**Comment by nedtwigg** [comment]
Great!  Glad you got it working.  If you have any other problems, just open an issue :)
