### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by CrazyCat88** [diffplug/matlabcontrol#6]
As I have read from the documentation, MatConsoleCtl uses several threads to handle a Matlab session. I’m running my application on a cluster, thus this is a huge problem.

Is there a possibility to force MatConsoleCtl not to create any new threads?

**Comment by nedtwigg** [comment]
If you're running your java code inside of MATLAB, then no new threads are created.

If you're running your java code outside of MATLAB, then [one thread is created inside of MATLAB to listen for commands and send data back.](https://github.com/diffplug/matconsolectl/blob/ffb79c619f95c75de61919a6d2c24b776745e586/src/matlabcontrol/MatlabConnector.java#L40).

I don't think you can get any more efficient than that, but I'm always open to ideas and PRs :)
