### ISSUE TITLE
getRealArray2D doesn't return right value

### ISSUE THREAD

**Issue by kusan-reveur** [diffplug/matlabcontrol#8]
Hi,

getRealArray2D  doesn't return the right value for decimal values.
1.19 end up becoming 1186.428...
I'm running on a Windows Systen in French which might be the reason (where dot is the sepator for thousands)? Also is it possible to get the right conversion from float to double?

Thank you in advance,

**Comment by nedtwigg** [comment]
I'm guessing this was closed on accident?  I don't have time to look into this at the moment, but if true this is definitely a bug which should get fixed!  Thanks for reporting.

**Comment by kusan-reveur** [comment]
No, it was my fault, I was using a library to plot the values and I think the problem comes from that another library.
For the loss of precision, I think it's due to the use of IEE754 for floating points (see http://stackoverflow.com/questions/6713673/precision-error-with-floats-in-java). So it's actually normal)
